### ISSUE TITLE
Add volume measures instead of weight

### ISSUE THREAD

**Issue by xiaoxu193** [hendricius/the-bread-code#18]
Hard to measure out how much is 200g of of water of 100g of flour... would be helpful to have volume measures like how many cups

**Comment by hendricius** [comment]
I usually have a scale. It can switch between ounces and grams. I like to use the scale because then it is really 100% exact.

Try to get a scale at around 20-30$. Some super cheap ones can not properly measure tiny changes. However a little bit too much salt can already make the difference or ruin the taste.

**Comment by mistressofjellyfish** [comment]
Additionally, 100g water = 100ml = 0.1 l which should be easily measurable.

That is, as long as you use a even halfway decent measuring system like the same world does.

**Comment by hendricius** [comment]
Closing this issue as of now. Feel free to provide a PR with adjustments :)
