### ISSUE TITLE
Doubling the starter

### ISSUE THREAD

**Issue by chaparin** [hendricius/the-bread-code#36]
Let's say I've succeeded with my starter and it yields good bread, does anyone have an effective instruction on doubling the size of the existing starter (Sauerteig im Deutsch?), without starting a new batch? By the way, I spent 2 years in Bavaria - the beer and bread heaven!

**Comment by hendricius** [comment]
Yes, just feed it heavily. Wait for a day or so, then you will have it doubled.

Assuming you have 200 grams of starter ready. You want 400 grams of starter. Take your starter and feed it with 100 grams of flour and 100 grams of water. Then you will have 400 grams of starter.

The more flour you add to the starter the longer it takes for it to be ready for bake. That's why I usually feed the starter 1 day before the actual baking. That way it becomes nicely sour.
