### ISSUE TITLE
Mistake on basic sour dough ingredients

### ISSUE THREAD

**Issue by Kohach** [hendricius/the-bread-code#92]
On the salt quantity calculation you said "One percent of 500 grams + 100 grams is 600 grams"
Do you mean "One percent of 500 grams + 100 grams is **6 grams**" ?

**Comment by clehene** [comment]
Also you mention a 40:60 sourdough:dough ratio but the actual quantities are ~ 200:800
https://github.com/hendricius/the-bread-code/blob/master/basics/basic-sour-dough.md
> In a new, large bowl mix and knead 500 grams of flour with 325 grams of water and 12 grams of salt
Add the sour dough (~200 grams) to the new bowl

**Comment by hendricius** [comment]
@clehene the percentages are always calculated based on the amount of flour that you add. 500 grams of flour. Of the 500 grams of flour, 40% starter. Hope this helps.

**Comment by clehene** [comment]
@hendricius I see, but it's, then the equivalent of 40% of 500 that is added to 500 so that would end up  roughly 29-30% of the mixed content. 
Perhaps it's just a matter of knowing how baker ratios work, but it's pretty confusing for me as a computer scientist as I wasn't sure how to figure out whether I got it right. I thought an additional note  may help.
